version: 2

sources:
  - name: dev
    database: japan
    schema: dev
    tables:
      - name: SRC_BANK_TRANSACTIONS
        loaded_at_field: CREATED_TS
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

